#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))


@test(5, "sort, file")
def test_sort_file():
    r.run_qemu(shell_script([
        'echo 3 8 9 1 3 5 > file.txt',
        'sort file.txt',
    ]))
    r.match('1 3 3 5 8 9', no=["exec .* failed", "cannot open"])


@test(5, "sort, file no arguments")
def test_sort_file_no_args():
    r.run_qemu(shell_script([
        'echo 3 8 9 1 3 5 | sort',
    ]))
    r.match('1 3 3 5 8 9', no=["exec .* failed", "cannot open"])


run_tests()
