#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(0, "running kalloctest")
def test_kalloctest():
    r.run_qemu(shell_script([
        'kalloctest'
    ]), timeout=300)
    
@test(5, "kalloctest: test1", parent=test_kalloctest)
def test_kalloctest_test1():
    r.match('^test1 OK$')
    
@test(5, "kalloctest: test2", parent=test_kalloctest)
def test_kalloctest_test2():
    r.match('^test2 OK$')

@test(5, "kalloctest: test3", parent=test_kalloctest)
def test_kalloctest_test3():
    r.match('^test3 OK$')

@test(5, "kalloctest: test4", parent=test_kalloctest)
def test_kalloctest_test4():
    r.match('^test4 OK$')

@test(5, "kalloctest: sbrkmuch")
def test_sbrkmuch():
    r.run_qemu(shell_script([
        'usertests sbrkmuch'
    ]), timeout=90)
    r.match('^ALL TESTS PASSED$')

@test(0, "running rwlktest")
def test_rwlktest():
    r.run_qemu(shell_script([
        'rwlktest'
    ]), timeout=150)
    
@test(20, "rwlktest", parent=test_rwlktest)
def test_bcachetest_checktest0():
    r.match('^rwlktest: 4/4 CPUs succeeded$')
    
@test(10, "usertests")
def test_usertests():
    r.run_qemu(shell_script([
        'usertests -q'
    ]), timeout=500)
    r.match('^ALL TESTS PASSED$')

run_tests()
